#!/bin/sh
bspc monitor -d 1 2 3 4 5 6
bspc config top_padding 42
bspc config bottom_padding 12
bspc config right_padding 12
bspc config left_padding 12
bspc config top_monocle_padding -4
bspc config bottom_monocle_padding -12
bspc config right_monocle_padding -12
bspc config left_monocle_padding -12
bspc config border_width         2
bspc config window_gap           6
bspc config normal_border_color		'#181F21'	
bspc config focused_border_color        '#E5C76B'
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
killall picom &
feh --bg-fill ~/Imágenes/NUEVO_FONDO.png 
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch_bar &
picom -b &
numlockx &
#xset s 600 &
#xss-lock ~/.config/bspwm/scripts/mylock.sh +resetsaver &
#/lib/mate-polkit/polkit-mate-authentication-agent-1 &
