#!/bin/sh
bspc monitor -d 1 2 3 4 5 6
bspc config top_monocle_padding -1 &
bspc config border_width         2 &
bspc config window_gap           6 &
bspc config normal_border_color			'#0f1417'	
bspc config focused_border_color    '#e06e6e'
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
killall picom &
feh --bg-fill ~/.config/bspwm/wallpaper.png 
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch_bar &
picom -b &
numlockx &
#mpd-mpris -host 127.0.0.1 &
